name: CI - Validacion de Calidad

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Usamos la 22 que es la más estable ahora
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Generar cliente de Prisma
        run: npx prisma generate

      - name: Ejecutar Build
        run: npm run build
        env:
          # Usamos una URL válida en formato, aunque sea local e inexistente en el runner
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/unused"
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'secret-provisorio-de-32-caracteres' }}
          NEXTAUTH_URL: "http://localhost:3000"