name: CI - Validacion de Calidad

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Generar cliente de Prisma
        run: npx prisma generate

      - name: Ejecutar Linter
        run: npm run lint

      - name: Ejecutar Build (Compilacion)
        run: npx next build --no-lint
        env:
          SKIP_ENV_VALIDATION: "true"
          NEXTAUTH_SECRET: "12345678901234567890123456789012"
          NEXTAUTH_URL: "http://localhost:3000"
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          # Esta variable es el "santo grial" para saltar validaciones de Prisma
          PRISMA_CLIENT_ENGINE_TYPE: "library"
          NODE_ENV: "production"