name: CI - Validacion de Calidad

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # <--- Actualizamos a la 24 para quitar el warning
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Generar cliente de Prisma
        run: npx prisma generate

      - name: Ejecutar Linter
        run: npm run lint

      - name: Ejecutar Build (Compilacion)
        run: npm run build
        env:
          # El combo definitivo de variables para engañar al build
          NEXT_PRIVATE_LOCAL_WEBPACK: "true"
          SKIP_ENV_VALIDATION: "true"
          NEXTAUTH_SECRET: "static_secret_for_build_only_12345"
          NEXTAUTH_URL: "http://localhost:3000"
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          PRISMA_CLIENT_ENGINE_TYPE: "library"
          NODE_ENV: "production"